name: CI

on: workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update
      run: apt update && apt upgrade
    - name: Download Ngrok
      run: apt install curl unzip
    - name: Ngrok Down
      run: curl https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip -o ngrok.zip
    - name: Extract Ngrok Archive
      run: unzip ngrok.zip
    - name: Auth
      run: .\ngrok\ngrok authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
